name: docker-ecr-publish
description: Plugin for building, tagging, caching and publishing images to AWS ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    dockerfile:
      type: string
    ecr-name:
      type: string
    args:
      type: [ string, array ]
    additional-tags:
      type: array
  required: []
