name: Docker ECR Publish
description: Build, tag, and push Docker images to Amazon ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    args:
      type: [array, string]
    branch-tags:
      type: array
    cache-from:
      type: [array, string]
    default-tags:
      type: array
    dockerfile:
      type: string
    ecr-name:
      type: string
  required: ['ecr-name']
