name: Docker ECR Publish
description: Plugin for building, tagging, caching and publishing images to AWS ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    args:
      type: [array, string]
    branch-tags:
      type: array
    default-tags:
      type: array
    dockerfile:
      type: string
    ecr-name:
      type: string
  required: []
